### ISSUE TITLE
Config missing new class definition (after pull)

### ISSUE THREAD

**Issue by mkucharz** [Syncano/syncano-cli#19]
1. syncano pull (on empty instance)
2. add class via dashboard (name "order", only one field: "author" which is reference to "user_profile")
3. syncano pull (no error)
4. class "order" missing in the config file

**Comment by mkucharz** [comment]
I tried to do `syncano pull picoblocks -c order` and.. now I have this class in config file:

```
morbo% cat syncano.yml                                                                                                                                                                                                                                 ~/Documents/picoblocks
classes:
  order:
    fields:
      author: reference user_profile filtered ordered
    group_permissions: create_objects
    other_permissions: create_objects
scripts: []
```

but... when I'm trying to push:

```
morbo% syncano pull picoblocks                                                                                                                                                                                                                         ~/Documents/picoblocks
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/syncano", line 9, in <module>
    load_entry_point('syncano-cli==0.3', 'console_scripts', 'syncano')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/syncano_cli/main.py", line 145, in main
    namespace.project = Project.from_config(namespace.file)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/syncano_cli/project.py", line 30, in from_config
    project.validate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/syncano_cli/project.py", line 87, in validate
    validate_classes(self.classes)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/syncano_cli/classes.py", line 165, in validate_classes
    .format(name, field, field_spec['target'])
ValueError: order.author references not defined class user_profile
```

**Comment by MariuszWisniewski** [comment]
@mkucharz Have you checked if the issue still exists with the new CLI version?
