### ISSUE TITLE
ConfigParser error on login

### ISSUE THREAD

**Issue by Eggwise** [Syncano/syncano-cli#69]
Installed the cli on my mac with pip (python3.5)

When i try to log in with
`syncano login --instance-name patient-resonance-4283`

i get the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/syncano", line 7, in <module>
    from syncano_cli.main import main
  File "/usr/local/lib/python3.5/site-packages/syncano_cli/main.py", line 6, in <module>
    from syncano_cli.account.commands import top_account
  File "/usr/local/lib/python3.5/site-packages/syncano_cli/account/commands.py", line 2, in <module>
    from syncano_cli.account.command import AccountCommands
  File "/usr/local/lib/python3.5/site-packages/syncano_cli/account/command.py", line 4, in <module>
    from syncano_cli.config import ACCOUNT_CONFIG
  File "/usr/local/lib/python3.5/site-packages/syncano_cli/config.py", line 4, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'

```

**Comment by opalczynski** [comment]
@Eggwise Hi, currently CLI do no support python3. Have it on the road map - will let you know :)
