### ISSUE TITLE
syncano cli not working

### ISSUE THREAD

**Issue by Eggwise** [Syncano/syncano-cli#76]
```
⇒  syncano sync push
Traceback (most recent call last):
  File "/usr/local/bin/syncano", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/main.py", line 37, in main
    raise CLIBaseException(e.message)
syncano_cli.base.exceptions.CLIBaseException: source


```

**Comment by Eggwise** [comment]
Reinstalled syncano-cli from the develop branch.
`I log in`
`syncano sync pull`

then after
`syncano sync push`

i get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/syncano", line 11, in <module>
    load_entry_point('syncano-cli==0.7', 'console_scripts', 'syncano')()
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/main.py", line 34, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/sync/commands.py", line 40, in sync
    context.obj['project'] = Project.from_config(context.obj['file'])
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/sync/project.py", line 31, in from_config
    project.validate()
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/sync/project.py", line 104, in validate
    validate_scripts(self.scripts)
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/sync/scripts.py", line 209, in validate_scripts
    validate_script(s)
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/sync/scripts.py", line 185, in validate_script
    'Could not find script "{source}" file'.format(**script)
KeyError: u'source'

```

**Comment by Eggwise** [comment]
Retried.. now its working, i think the .sync file didnt get created.
