### ISSUE TITLE
Error when trying to host content

### ISSUE THREAD

**Issue by Eggwise** [Syncano/syncano-cli#83]
I try hosting a simple app in my folder named "hosting" using the syncano host command.
But its not working:

Previous conv: 
me:

> I heard you guys are working on webhosting, file storage etc. I would
> love to host some files on syncano. Could you tell me something about
> the plans for webhosting?

Syncano

> ..
> ...
> I can, you can actually already start using it! :) We're in the process
> of adding it to the Dashboard - for now, the easiest way to host files
> on Syncano is by using our CLI.
> 
> You can read about installing it here:
> https://github.com/Syncano/syncano-cli#installation and then just skipp
> directly to https://github.com/Syncano/syncano-cli#syncano-hosting to
> read about hosting.
> 
> In short you need to:
> 1. Install it
> 
> pip install syncano-cli
> 1. Login to your instance
> 
> syncano login --instance-name your-instance-name
> 1. syncano hosting publish /path/to/directory
> 
> Wait until it finishes and that's it!
> 
> Your website will be available under your-instance-name.syncano.site
> domain, with SSL. We'll be adding custom domains later, sometime in Q4.
> 
> Let me know if that works for you!
> 
> Thanks for creating an issue on GitHub. I assigned our developer to it
> and will test it and fix it when we find the bug. Thanks again!

I try hosting a simple app in my folder named "hosting" using the syncano host command.
When i type:

```
syncano hosting publish hosting  
```

I get the following error 

```
INFO: Uploading file: json_viewer/favicon.ico
INFO: Uploading file: json_viewer/index.html
INFO: Uploading file: json_viewer/static/css/main.cacbacc7.css
INFO: Uploading file: json_viewer/static/css/main.cacbacc7.css.map
INFO: Uploading file: json_viewer/static/js/main.97bcc040.js
INFO: Uploading file: json_viewer/static/js/main.97bcc040.js.map
INFO: Uploading file: json_viewer/static/media/logo.5d5d9eef.svg
Traceback (most recent call last):
  File "/usr/local/bin/syncano", line 11, in <module>
    load_entry_point('syncano-cli==0.7', 'console_scripts', 'syncano')()
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/main.py", line 34, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/syncano_cli/hosting/commands.py", line 43, in publish
    domain=domain
KeyError: 'instance_name'
```

**Comment by opalczynski** [comment]
Hi @Eggwise If I am right - this was corrected in 0.8 version of CLI. Btw. - your hosting is published, the error is attached to the information string diplayed by CLI after publishing all the files. Just go to: `<instance-name>.syncano.site`
